### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by remy** [andybelldesign/hylia#48]
Error after clean install:

```
[3] Eleventy fatal error: (more in DEBUG output)
[3] > Error in your Eleventy config file '/Users/remy/Sites/scratch/hylia/.eleventy.js'. You may need to run `npm install`. (EleventyConfigError)
[3] > Cannot find module '../build/default/canvas' (Error):
[3]     Error: Cannot find module '../build/default/canvas'
[3]         at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
[3]         at Function.Module._load (internal/modules/cjs/loader.js:506:25)
[3]         at Module.require (internal/modules/cjs/loader.js:636:17)
[3]         at require (internal/modules/cjs/helpers.js:20:18)
[3]         at Object.<anonymous> (/Users/remy/Sites/scratch/node_modules/canvas/lib/bindings.js:7:20)
[3]         at Module._compile (internal/modules/cjs/loader.js:688:30)
[3]         at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[3]         at Module.load (internal/modules/cjs/loader.js:598:32)
[3]         at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[3]         at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by andybelldesign** [comment]
Cheers @remy, as I’ve said away from here, I can't recreate, but I'll ask folks on Twitter if they can.

**Comment by remy** [comment]
I think this is actually my setup:

```
/Users/remy/Sites/scratch/node_modules/canvas/lib/bindings.js
```

This is referring to the `node_modules` in the _parent_ directory, not the cwd.

---

Just confirmed - nm, like I said, magnet for bugs (even if they're not yours!)

**Comment by andybelldesign** [comment]
Thanks for clearing that up, @remy. Panic over!
