### ISSUE TITLE
Using Netlify dev instead of NPM start (Solved)

### ISSUE THREAD

**Issue by alolalo** [andybelldesign/hylia#55]
Since Netlify is part of the setup I figured that it would use `$netlify dev` as well to give myself a break (designer who can code) as npm and node are my least favorite tools to use (love Poi, Compass, Netlify as a designer who codes and dislikes CLI's & greedcorps). 

To reproduce simply one-click-deploy a hylia, clone the repo locally, and run `$netlify dev` “error” (it's not) displayed the following;

Having trouble rendering njk template ./src/admin.njk (TemplateContentRenderError)
> (unknown path)
  Error: template not found: assets/css/global.css (Template render error):
    Template render error: (unknown path)
      Error: template not found: assets/css/global.css
        at Object._prettifyError (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/lib.js:36:11)
        at /Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/environment.js:567:19
        at eval (eval at _compile (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:14:11)
        at createTemplate (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/environment.js:295:11)
        at next (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/lib.js:282:7)
        at handle (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/environment.js:329:11)
        at /Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/environment.js:339:9
        at next (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/lib.js:280:7)
        at Object.asyncIter (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/lib.js:286:3)
        at Environment.getTemplate (/Users/ghoeve/Documents/blog/blog-hylia/node_modules/nunjucks/src/environment.js:321:9)

**Comment by andybelldesign** [comment]
Ah I think I know what's going on here. The way that the CSS is pulled into the theme is that Sass generates `global.css` into the `_includes` folder. When you're running `$netlify dev`, it’s probably not running the right command.

Is there a way you can select which npm script runs in that setup?

**Comment by sdras** [comment]
I really wouldn't recommend using netlify dev for this- but if you do want to alter what happens with npm start, you shouldn't change the command npm start, you should alter what happens with that command (npm start can be used to trigger a lot of different actions). 

In the future, we're going to be working on the Netlify dev experience a bunch, but while it's in beta I wouldn't alter your workflow this way personally.

**Comment by andybelldesign** [comment]
Thanks for the knowledge, @sdras 🙌

I don't know much about Netlify local, so I'm glad you stopped by 🙂

**Comment by alolalo** [comment]
Thank you for coming back on this @sdras! on Twitter! Good to know
